services:
  - type: web
    name: hurricane-tracker
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: |
      python manage.py migrate --noinput && \
      (python import_shelters.py || true) && \
      gunicorn hurricane_project.wsgi:application --workers 2 --threads 4 --timeout 120
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
