# Generated by Django 5.2.4 on 2025-07-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_shelter_latitude_shelter_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
