# Generated by Django 5.2.4 on 2025-07-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_shelter_latitude_alter_shelter_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shelter',
            name='is_pet_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shelter',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
