# Generated by Django 5.2.4 on 2025-07-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_shelter_capacity_shelter_is_pet_friendly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelter',
            name='x',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelter',
            name='y',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
