# Generated by Django 5.2.4 on 2025-07-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_shelter_x_shelter_y'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelter',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='is_pet_friendly',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='notes',
        ),
        migrations.AddField(
            model_name='shelter',
            name='city',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelter',
            name='county',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelter',
            name='zip_code',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shelter',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
