# Generated by Django 5.2.4 on 2025-07-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_remove_shelter_capacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shelter',
            old_name='x',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='shelter',
            old_name='y',
            new_name='longitude',
        ),
        migrations.AddField(
            model_name='shelter',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shelter',
            name='is_pet_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shelter',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shelter',
            name='shelter_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shelter',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
