# Generated by Django 5.2.4 on 2025-08-06 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_subscriber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriber',
            old_name='subscribed_at',
            new_name='timestamp',
        ),
    ]
